###################### Baseline GWN args, default arguments are optimal hyper-parameters ######################
device:
  type: str
  default: cpu
  help: device to place model on
data:
  type: str
  default: 'DataNew/Graph Neural Network Data/Graph Station Data/Graph.csv' #DataNew
  help: data path
adjdata:
  type: str
  default: 'DataNew/Graph Neural Network Data/Adjacency Matrix/adj_mx.pkl'  #DataNew
  help: adj data path
adjtype:
  type: str
  default: doubletransition
  help: adj type
gcn_bool:
  type: bool
  default: true
  help: whether to add graph convolution layer
aptonly:
  type: bool
  default: true
  help: whether only adaptive adj
addaptadj:
  type: bool
  default: true
  help: whether add adaptive adj
randomadj:
  type: bool
  default: true
  help: whether random initialize adaptive adj
seq_length:
  type: int
  default: 24
  help: length of output sequence
lag_length:
  type: int
  default: 12
  help: length of input sequence
nhid:
  type: int
  default: 32
  help: ''
in_dim:
  type: int
  default: 6
  help: number of features in input
num_layers:
  type: int
  default: 2
  help: number of layers
batch_size:
  type: int
  default: 64
  help: batch size
patience:
  type: int
  default: 9
  help: patience
learning_rate:
  type: float
  default: 0.001
  help: learning rate
dropout:
  type: float
  default: 0.3
  help: dropout rate
weight_decay:
  type: float
  default: 0.0001
  help: weight decay rate
epochs:
  type: int
  default: 3
  help: ''
save:
  type: str
  default: 'Garage/Final Models/GWN/'
  help: save path

