# Configuration pyyaml file with configuration settings required (as args) for main.py

############################ Train baselines (GWN & TCN) ############################
train_tcn:
  type: bool
  default: false
  help: whether to train final TCN models
train_gwn:
  type: bool
  default: false
  help: whether to train final GWN model

############################ Random Search HPO arguments (GWN & TCN) ############################ 
tune_tcn:
  type: bool
  default: false
  help: whether to perform random search HPO on TCN models
tune_gwn:
  type: bool
  default: false
  help: whether to perform random search HPO on GWN model
num_configs:
  type: int
  default: 30
  help: number of random configurations to search through

############################ Perform evaluations calculating metrics of final models' results (GWN & TCN) ############################
eval_tcn:
  type: bool
  default: false
  help: whether to report final TCN metrics
eval_gwn:
  type: bool
  default: false
  help: whether to report final GWN metrics

############################ General data configurations ############################
increment: 
  type: int[]
  default: [100,200,300,8760, 10920, 13106, 15312, 17520, 19704, 21888, 24096, 26304,
                 28464, 30648, 32856, 35064, 37224, 39408, 41616, 43824, 45984,
                 48168, 50376, 52584, 54768, 56952, 59160, 61368, 63528, 65712,
                 67920, 70128, 72288, 74472, 76680, 78888, 81048, 83232, 85440,
                 87648, 89832, 92016, 94224, 96432, 98592, 100776, 102984, 105192,
                 107352, 109536, 111744, 113929]
  help:  List of points to split data in train, validation, and test sets for walk-forward validation. The first marker, 
    8784 is one year's worth of data, the next step is 3 months of data, and the following step is also 3 months of 
    data, resulting in rolling walk-forward validation where the train size increases each increment, with the 
    validation and test sets each being 3 months' worth of data.

stations:
  type: str[]
  # default: ['Atlantis', 'Calvinia WO', 'Cape Columbine', 'Cape Point',
  #               'Cape Town - Royal Yacht Club', 'Cape Town Slangkop', 'Excelsior Ceres', 'Hermanus',
  #               'Jonkershoek', 'Kirstenbosch', 'Ladismith', 'Molteno Resevoir', 'Paarl',
  #               'Porterville', 'Robben Island', 'Robertson', 'SA Astronomical Observatory',
  #               'Struisbaai', 'Tygerhoek', 'Wellington', 'Worcester AWS']
  default: ['ADDO ELEPHANT PARK', 'ALEXANDERBAAI', 'ALIWAL-NORTH PLAATKOP', 'BARKLY-OOS (CAERLEON)',
                'BRANDVLEI', 'CALVINIA WO', 'CAPE TOWN WO', 'DE AAR WO', 'DOHNE - AGR', 'EAST LONDON WO',
                'EXCELSIOR CERES', 'FORT BEAUFORT', 'FRASERBURG', 'GEORGE WITFONTEIN', 'GEORGE WO', 
                'GRAAFF - REINET', 'GRAHAMSTOWN', 'KOINGNAAS', 'LADISMITH', 'LAINGSBURG', 'LANGGEWENS',
                'MALMESBURY', 'MOLTENO RESERVOIR','NOUPOORT','OUDTSHOORN', 'PATENSIE','POFADDER', 
                'PORT ALFRED - AIRPORT','PORT ELIZABETH AWOS', 'PORT ELIZABETH AWS','PORT NOLLOTH','PORTERVILLE', 
                'PRIESKA', 'REDELINGSHUYS-AWS','RIVERSDALE','SOMERSET EAST','SPRINGBOK WO','TWEE RIVIEREN',
                'UITENHAGE','UPINGTON WO', 'VANWYKSVLEI','VIOOLSDRIF - AWS','VREDENDAL','WILLOWMORE','WORCESTER-AWS']
  help: list of all stations names

horizons:
  type: int[]
  default: [3, 6, 9, 12, 24]
  help: forecast horizons

n_stations:
  type: int
  default: 45
  help: number of weather stations

n_split:
  type: int
  default: 47
  help: number of splits in walk-forward validation

################################# Loss and Optimizer  ###############################

loss_function:
  type: string
  default: 'MSE'     #Only accepts MSE, MAE, sparse_categorical_crossentropy, categorical_crossentropy.
  help: type of loss function used (to add another method look at User Guide), default type set to MSE

optimizer:
  type: string
  default: 'Adam'     #Only accepts Adam, SGD, RMSprop.
  help: type of optimizers used for model (to add another method look at User Guide), default type set to Adam

############################ Visualise Adjacency Matrix ############################
vis:
  type: bool
  default: false
  help: whether to create visualisations
modelVis:
  type: str
  default: GWN
  help: the model to visualise
horizonVis:
  type: str
  default: "3"
  help: the horizon to visualise
splitVis:
  type: str
  default: 0
  help: the split number up to which visualisations should be generated for
locations_path:
  type: str
  default: 'DataNew/Locations/Locations.csv'
  help: path to csv containg station coordinates