train_gwn:
  type: bool
  default: true
  help: whether to train final GWN model
############################ General data configurations ############################
increment:
  type: int[]
  default: [52560, 61320, 70080]
  help:  (from davidson) List of points to split data in train, validation, and test se$
    8784 is one year's worth of data, the next step is 3 months of data, and the follow$
    data, resulting in rolling walk-forward validation where the train size increases e$
    validation and test sets each being 3 months' worth of data.

stations:
  type: str[]
  default: ['ADDO ELEPHANT PARK', 'ALEXANDERBAAI', 'ALIWAL-NORTH PLAATKOP', 'BARKLY-OOS (CAERLEON)',
                'BRANDVLEI', 'CALVINIA WO', 'CAPE TOWN WO', 'DE AAR WO', 'DOHNE - AGR', 'EAST LONDON WO',
                'EXCELSIOR CERES', 'FORT BEAUFORT', 'FRASERBURG', 'GEORGE WITFONTEIN', 'GEORGE WO', 
                'GRAAFF - REINET', 'GRAHAMSTOWN', 'KOINGNAAS', 'LADISMITH', 'LAINGSBURG', 'LANGGEWENS',
                'MALMESBURY', 'MOLTENO RESERVOIR','NOUPOORT','OUDTSHOORN', 'PATENSIE','POFADDER', 
                'PORT ALFRED - AIRPORT','PORT ELIZABETH AWOS', 'PORT ELIZABETH AWS','PORT NOLLOTH','PORTERVILLE', 
                'PRIESKA', 'REDELINGSHUYS-AWS','RIVERSDALE','SOMERSET EAST','SPRINGBOK WO','TWEE RIVIEREN',
                'UITENHAGE','UPINGTON WO', 'VANWYKSVLEI','VIOOLSDRIF - AWS','VREDENDAL','WILLOWMORE','WORCESTER-AWS']
  help: list of all stations names

horizons:
  type: int[]
  default: [3, 6]
  help: forecast horizons

n_stations:
  type: int
  default: 45
  help: number of weather stations

n_split:
  type: int
  default: 1
  help: number of splits in walk-forward validation

############################ Visualise Adjacency Matrix ############################
vis:
  type: bool
  default: false
  help: whether to create visualisations

modelVis:
  type: str
  default: GWN
  help: the model to visualise

horizonVis:
  type: str
  default: "3"
  help: the horizon to visualise

splitVis:
  type: str
  default: 2
  help: the split number up to which visualisations should be generated for

locations_path:
  type: str
  default: 'DataNew/Locations/Locations.csv'
  help: path to csv containg station coordinates
